CREATE TABLE `nutricao`.`Aminoacidostaco3` ( `id` INT(3) NOT NULL AUTO_INCREMENT ,  
                              `numeroAlimento` VARCHAR(10) NOT NULL, 
                              `descricaoAlimento` VARCHAR(255) NOT NULL, 
                              `triptofano` VARCHAR(20) NOT NULL, 
                              `treonina` VARCHAR(20) NOT NULL, 
                              `isoleucina` VARCHAR(20) NOT NULL, 
                              `leucina` VARCHAR(20) NOT NULL, 
                              `lisina` VARCHAR(20) NOT NULL,
                              `metionina` VARCHAR(20) NOT NULL,
                              `cistina` VARCHAR(20) NOT NULL, 
                              `fenilalanina` VARCHAR(20) NOT NULL, 
                              `tirosina` VARCHAR(20) NOT NULL, 
                              `valina` VARCHAR(20) NOT NULL, 
                              `arginina` VARCHAR(20) NOT NULL, 
                              `histidina` VARCHAR(20) NOT NULL, 
                              `alanina` VARCHAR(20) NOT NULL, 
                              `acidoAspartico` VARCHAR(20) NOT NULL, 
                              `acidoClutamico` VARCHAR(20) NOT NULL, 
                              `glicina` VARCHAR(20) NOT NULL, 
                              `prolina` VARCHAR(20) NOT NULL, 
                              `serina` VARCHAR(20) NOT NULL, 
                              `created_at` VARCHAR(30) NOT NULL,
                              `updated_at` VARCHAR(30) NOT NULL,
                              PRIMARY KEY (`id`)) ENGINE = InnoDB;
